annotations:
  category: Analytics
apiVersion: v2
appVersion: 4.4.1
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 1.x.x
name: grafana-operator
version: 2.6.2
